#ifndef __EEPROM_IDS
#define __EEPROM_IDS

/* Exported constants ------------------------------------------------------*/
#define LATTICE_CALIBRATION_POLY_EEID 0
#define LATTICE_CONSTRAINTS_EEID 1
#define LATTICE_DEVICE_INFO_EEID 2
#define LATTICE_SEARCHING_PARAMS_EEID 3
#define LATTICE_POWER_TRACKING_PID_PARAMS_EEID 4
#define LATTICE_FREQUENCY_TRACKING_PID_PARAMS_EEID 5
#define LATTICE_TRACKING_DESTINATION_POWER_EEID 6

#endif